# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='addr',
            field=models.CharField(default='panda', max_length=256),
            preserve_default=False,
        ),
    ]
