# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 07:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_person1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person1',
        ),
    ]
