# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_delete_person1'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.CharField(default=18, max_length=4),
            preserve_default=False,
        ),
    ]
