# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 05:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20161128_0554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='entry',
        ),
    ]
