# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 01:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_person_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='entry',
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
