# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 03:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20161129_0344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='entry',
        ),
        migrations.AddField(
            model_name='employee',
            name='entry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Entry'),
            preserve_default=False,
        ),
    ]
