# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_employee_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='data',
            field=models.CharField(default=1, max_length=1024),
            preserve_default=False,
        ),
    ]
