# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 03:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_entry_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='data',
        ),
    ]
