# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_remove_entry_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='sex',
            field=models.CharField(choices=[('f', 'famale'), ('m', 'male')], default=1, max_length=4),
            preserve_default=False,
        ),
    ]
