# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20161205_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userform',
            name='img',
            field=models.FileField(upload_to='F:\\pythonCode\\project/recv/'),
        ),
    ]
