# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20161205_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='userform',
            name='age',
            field=models.IntegerField(default=18),
            preserve_default=False,
        ),
    ]
